export const coins = [
    {
      AAVE: "Aave",
      ABFY: "Ambify",
      ACH: "Alchemy Pay",
      ACMFT: "AC Milan",
      ACORDO01: "None",
      ADA: "Cardano",
      ADS: "Adshares",
      AGIX: "SingularityNET",
      AIOZ: "Aioz",
      ALCX: "Alchemix",
      ALGO: "Algorand",
      ALICE: "MyNeighborAlice",
      ALLFT: "Alliance",
      ALPHA: "Alpha Venture Dao",
      AMFT: "Aston Martin Cognizant",
      AMP: "Amp",
      ANKR: "ANKR",
      ANT: "Aragon",
      APE: "ApeCoin",
      API3: "API3",
      APT: "Aptos",
      ARGFT: "Argentine Football Association",
      ASRFT: "AS Roma",
      ATLAS: "Star Atlas",
      ATMFT: "Fan Token ATM",
      ATOM: "Cosmos",
      AUDIO: "Audius",
      AVAX: "Avalanche",
      AXS: "Axie Infinity",
      BADGER: "Badger DAO",
      BAL: "Balancer",
      BAND: "Band Protocol",
      BARFT: "FC Barcelona",
      BAT: "Basic Attention token",
      BCH: "Bitcoin Cash",
      BICO: "Biconomy",
      BLZ: "Bluzelle",
      BNT: "BANCOR",
      BTB05: "BT Token Black 05",
      BTB10: "BT Token Black 10",
      BTC: "Bitcoin",
      BTRST: "Braintrust",
      CAIFT: "Fan Token CAI",
      CEEK: "CEEK VR",
      CHZ: "Chiliz",
      CITYFT: "Manchester City FC",
      CLV: "Clover Finance",
      COMP: "Compound",
      CONS01: "Consorcio 01",
      COTI: "COTI",
      CRV: "Curve Dao Token",
      CTSI: "Cartesi",
      CVC: "Civic",
      CVX: "Convex Finance",
      DAI: "Dai",
      DG: "Decentral Games",
      DIA: "DIA",
      DOGE: "Dogecoin",
      DOT: "Polkadot",
      DPI: "DeFi Pulse Index",
      DYDX: "dYdX",
      ENER01: "Token de Energia",
      ENER02: "Energia 02",
      ENER03: "Energia 03",
      ENJ: "Enjin Coin",
      ENS: "Ethereum Name Service",
      ERN: "Ethernity",
      ETH: "Ethereum",
      FARM: "Harvest Finance",
      FET: "Fetch.ai",
      FIL: "Filecoin",
      FLOKI: "Floki Inu",
      FLOW: "Flow",
      FTM: "None",
      GALA: "Gala",
      GALFT: "Galatasaray",
      GALOFT: "Clube Atletico Mineiro",
      GHST: "Aavegotchi",
      GMT: "STEPN",
      GNO: "Gnosis",
      GODS: "Gods Unchained",
      GRT: "The Graph",
      GST: "Green Satoshi Token",
      HIGH: "Highstreet",
      HNT: "None",
      HOT: "Holo",
      ICP: "Internet Computer",
      ILV: "Illuvium",
      IMOB01: "None",
      IMOB02: "None",
      IMX: "Immutable X'",
      INTERFT: "Inter Milan",
      JASMY: "JasmyCoin",
      JUVFT: "Juventus",
      KEEP: "Keep Network",
      KNC: "Kyber Network",
      KP3R: "Keep3rV1",
      KSM: "Kusama",
      LDO: "Lido DAO Token",
      LINK: "Chainlink",
      LOOKS: "LooksRare",
      LPT: "Livepeer",
      LQTY: "Liquity",
      LRC: "Loopring",
      LTC: "Litecoin",
      MANA: "MANA (Decentraland)",
      MATIC: "Polygon",
      MBRL: "MBRL",
      MBSANTOS01: "Token da Vila",
      MBTKN01: "MB TOKEN",
      MBVASCO01: "Vasco Token",
      MC: "Merit Circle",
      MCO2: "Moss Carbon Credit",
      MENGOFT: "Flamengo",
      METIS: "MetisDAO",
      MINA: "Mina",
      MIR: "Mirror Protocol",
      MKR: "Maker",
      MPL: "Maple",
      MVI: "Metaverse Index",
      NAVIFT: "Natus Vincere",
      NFTOKN01: "Cesta de NFTs",
      NODL: "Nodle",
      OCEAN: "Ocean Protocol",
      OGFT: "OG eSports",
      OGN: "Origin Protocol",
      OMG: "Omg Network",
      OP: "Optimism",
      OPUL: "Opulous",
      OXT: "Orchid",
      PAXG: "PAX Gold",
      PERP: "Perpetual Protocol",
      PFLFT: "Professional Fighters League",
      PLA: "PlayDapp",
      POLS: "Polkastarter",
      POLY: "Polymath",
      PORFT: "Portugal National Team FT",
      POWR: "Power Ledger",
      PSGFT: "Paris",
      QNT: "Quant",
      RACA: "Radio",
      RAD: "Radicle",
      RARE: "SuperRare",
      RARI: "Rarible",
      REN: "Ren",
      REQ: "Request",
      RFDFP16: "Fluxos de Pagamento 16",
      RFDFP17: "Fluxo de Pagamentos 17",
      RLY: "Rally",
      RNDR: "Render Token",
      ROSE: "Oasis Network",
      SACI: "Sport Club Internacional",
      SAND: "The Sandbox",
      SAUBERFT: "Alfa Romeo Racing ORLEN",
      SCCPFT: "Corinthians",
      SDAO: "SingularityDAO",
      SHIB: "Shiba Inu",
      SKL: "SKALE Network",
      SLP: "Smooth",
      SNX: "Synthetix",
      SOL: "Solana",
      SPELL: "Spell",
      SPFCFT: "SPFC",
      SRM: "Serum",
      STG: "FInance",
      STORJ: "Storj",
      STVFT: "Sint",
      STX: "Stacks",
      SUPER: "SuperFarm",
      SUSHI: "SushiSwap",
      SYN: "Synapse",
      THFT: "Team",
      TLM: "Alien",
      TRB: "Tellor",
      TRU: "TrueFi",
      UFCFT: "UFC",
      UMA: "Uma",
      UNI: "Uniswap",
      USDC: "USD Coin",
      USDP: "Pax Dollar",
      VERDAO: "Sociedade Esportiva Palmeiras",
      VSPRK01: "Precatorio VS SP01",
      WBTC: "Wrapped Bitcoin",
      WBX: "WiBX",
      WEMIX: "Wemix",
      WLUNA: "Wrapped LUNA Token",
      XLM: "Stellar",
      XRP: "XRP",
      XTZ: "Tezos",
      YBOFT: "BSC Young Boys",
      YFI: "yearn.finance",
      YGG: "Yield Guild Games",
      ZRX: "0x",
      ONS05BRL: "None",
      CSH08BRL: "None",
      P12BRL: "None",
      FTBRL: "None",
    },
  ];
